runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:02cuip8Yipc3qvVwBghVuryEmi8I1jF7v7uWDux2ebo=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: galaxia_lejana
  DB_USERNAME: root
  DB_PASSWORD: Nico2019
  DB_SOCKET: "/cloudsql/api-project-1081911154385:southamerica-east1:galaxia-lejana"

beta_settings:
  cloud_sql_instances: "api-project-1081911154385:southamerica-east1:galaxia-lejana"